remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Apoorva Mahadik
description: Creative problem-solver engineering AI-driven systems. Turning complexity into clarity with curiosity, collaboration, and impact.
